import test from "node:test";import assert from "node:assert/strict";import {IdentityError,IdentityService} from "../src/identity/service.js";import type {IdentityRepository,SessionCreateInput} from "../src/identity/repository.js";import type {EncryptedNotification,IdentityActionPurpose,SessionRecord,UserRecord} from "../src/identity/types.js";
class MemoryRepository implements IdentityRepository{
 users:UserRecord[]=[];sessions:SessionRecord[]=[];tokens=new Map<string,{userId:string,purpose:IdentityActionPurpose}>();events:string[]=[];
 async createUser(i:{id:string;email:string;displayName:string;passwordHash:string}){const now=new Date().toISOString();const u:UserRecord={...i,status:"active",emailVerifiedAt:null,passwordChangedAt:now,authVersion:1,createdAt:now,updatedAt:now};this.users.push(u);return u;}
 async findUserByEmail(e:string){return this.users.find(u=>u.email===e)??null;}async findUserById(id:string){return this.users.find(u=>u.id===id)??null;}async upgradePasswordHash(id:string,h:string){const i=this.users.findIndex(u=>u.id===id);if(i>=0)this.users[i]={...this.users[i]!,passwordHash:h};}
 async issueActionToken(i:{id:string;userId:string;purpose:IdentityActionPurpose;tokenHash:string;expiresAt:string;notification:EncryptedNotification}){this.tokens.set(i.tokenHash,{userId:i.userId,purpose:i.purpose});}
 async verifyEmailWithToken(h:string){const t=this.tokens.get(h);if(!t||t.purpose!=="verify_email")return null;const i=this.users.findIndex(u=>u.id===t.userId);if(i<0)return null;this.users[i]={...this.users[i]!,emailVerifiedAt:new Date().toISOString()};this.tokens.delete(h);return this.users[i]!;}
 async resetPasswordWithToken(){return null;}async createSession(i:SessionCreateInput){const now=new Date().toISOString();const s:SessionRecord={...i,rotatedFromSessionId:i.rotatedFromSessionId??null,createdAt:now,lastSeenAt:now,revokedAt:null};this.sessions.push(s);return s;}async findActiveSessionByTokenHash(h:string){return this.sessions.find(s=>s.tokenHash===h&&!s.revokedAt)??null;}async touchSession(){}async rotateSession(){return null;}async listActiveSessions(uid:string){return this.sessions.filter(s=>s.userId===uid&&!s.revokedAt);}async revokeSession(h:string){const i=this.sessions.findIndex(s=>s.tokenHash===h);if(i>=0)this.sessions[i]={...this.sessions[i]!,revokedAt:new Date().toISOString()};}async revokeSessionById(){}async revokeAllSessions(){}async recordSecurityEvent(i:{eventType:string}){this.events.push(i.eventType);}
}
const secret=Buffer.alloc(32,1).toString("base64url");const fastPasswords={async hash(p:string){if(p.length<15)throw new Error();return `test:${p}`;},async verify(p:string,h:string){return{valid:h===`test:${p}`,needsRehash:false};}};
function service(repo:MemoryRepository){return new IdentityService(repo,{sessionAbsoluteTtlSeconds:3600,sessionIdleTtlSeconds:600,verificationTtlSeconds:900,passwordResetTtlSeconds:600,tokenPepper:secret,notificationKey:secret,passwords:fastPasswords});}
const context={ipHash:"i",userAgentHash:"u"};
test("registration is generic and creates an unverified account",async()=>{const r=new MemoryRepository();await service(r).register({email:"User@Example.com",displayName:"User",password:"a secure password value"},context);assert.equal(r.users[0]?.email,"user@example.com");assert.equal(r.users[0]?.emailVerifiedAt,null);assert.ok(r.events.includes("identity.registration_requested"));});
test("unverified users cannot login",async()=>{const r=new MemoryRepository();await service(r).register({email:"u@example.com",displayName:"User",password:"a secure password value"},context);await assert.rejects(()=>service(r).login({email:"u@example.com",password:"a secure password value"},context),(e:unknown)=>e instanceof IdentityError&&e.code==="email_verification_required");});
