import type { FastifyPluginAsync, FastifyReply, FastifyRequest } from "fastify";

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Phoenix Passkey Validation</title><link rel="stylesheet" href="/passkey-validation/style.css"></head>
<body><main><h1>Phoenix Passkey Validation</h1><p>This staging-only harness performs same-origin WebAuthn registration and authentication. Session tokens remain in memory and are never persisted.</p>
<section><h2>Environment</h2><button id="diagnose">Run diagnostics</button><pre id="diagnostics"></pre></section>
<section><h2>Register a passkey</h2><label>Session token <input id="sessionToken" type="password" autocomplete="off"></label><label>Label <input id="label" maxlength="64" value="Validation passkey"></label><button id="register">Register</button></section>
<section><h2>Authenticate with a passkey</h2><button id="authenticate">Authenticate</button></section>
<section><h2>Evidence</h2><button id="download">Download sanitized evidence</button><button id="clear">Clear</button><pre id="log"></pre></section>
</main><script type="module" src="/passkey-validation/app.js"></script></body></html>`;

const css = `:root{font-family:system-ui,sans-serif;color-scheme:light dark}body{max-width:880px;margin:2rem auto;padding:0 1rem}main{display:grid;gap:1rem}section{border:1px solid #8886;border-radius:.6rem;padding:1rem}label{display:block;margin:.6rem 0}input{width:min(100%,38rem);padding:.55rem}button{margin:.35rem .35rem .35rem 0;padding:.6rem .9rem}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#8881;padding:.75rem;border-radius:.4rem}`;

const javascript = String.raw`
const evidence={schema:"phoenix.passkey-validation.v1",startedAt:new Date().toISOString(),diagnostics:null,events:[]};
const $=id=>document.getElementById(id);
function record(type,outcome,details={}){evidence.events.push({at:new Date().toISOString(),type,outcome,...details});$("log").textContent=JSON.stringify(evidence.events,null,2);}
function b64uToBytes(value){const normalized=value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"=");const raw=atob(normalized);return Uint8Array.from(raw,c=>c.charCodeAt(0));}
function bytesToB64u(value){const bytes=new Uint8Array(value);let raw="";for(const byte of bytes)raw+=String.fromCharCode(byte);return btoa(raw).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function creationOptions(options){return {...options,challenge:b64uToBytes(options.challenge),user:{...options.user,id:b64uToBytes(options.user.id)},excludeCredentials:(options.excludeCredentials??[]).map(item=>({...item,id:b64uToBytes(item.id) }))};}
function requestOptions(options){return {...options,challenge:b64uToBytes(options.challenge),allowCredentials:(options.allowCredentials??[]).map(item=>({...item,id:b64uToBytes(item.id)}))};}
function registrationJSON(credential){const response=credential.response;return {id:credential.id,rawId:bytesToB64u(credential.rawId),type:credential.type,response:{clientDataJSON:bytesToB64u(response.clientDataJSON),attestationObject:bytesToB64u(response.attestationObject),transports:typeof response.getTransports==="function"?response.getTransports():[]},clientExtensionResults:credential.getClientExtensionResults(),authenticatorAttachment:credential.authenticatorAttachment??undefined};}
function authenticationJSON(credential){const response=credential.response;return {id:credential.id,rawId:bytesToB64u(credential.rawId),type:credential.type,response:{clientDataJSON:bytesToB64u(response.clientDataJSON),authenticatorData:bytesToB64u(response.authenticatorData),signature:bytesToB64u(response.signature),userHandle:response.userHandle?bytesToB64u(response.userHandle):undefined},clientExtensionResults:credential.getClientExtensionResults(),authenticatorAttachment:credential.authenticatorAttachment??undefined};}
async function api(path,init={}){const response=await fetch(path,{...init,headers:{"content-type":"application/json",...(init.headers??{})},credentials:"same-origin",redirect:"error"});const body=response.status===204?null:await response.json();if(!response.ok)throw new Error(body?.error??("http_"+response.status));return body;}
async function diagnostics(){const supported=typeof PublicKeyCredential!=="undefined"&&Boolean(navigator.credentials);let uvpaa=false,conditional=false;if(supported&&typeof PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable==="function")uvpaa=await PublicKeyCredential.isUserVerifyingPlatformAuthenticatorAvailable();if(supported&&typeof PublicKeyCredential.isConditionalMediationAvailable==="function")conditional=await PublicKeyCredential.isConditionalMediationAvailable();evidence.diagnostics={at:new Date().toISOString(),secureContext:isSecureContext,webAuthnSupported:supported,userVerifyingPlatformAuthenticator:uvpaa,conditionalMediation:conditional,platform:navigator.userAgentData?.platform??navigator.platform??"unknown"};$("diagnostics").textContent=JSON.stringify(evidence.diagnostics,null,2);record("diagnostics","success");}
$("diagnose").addEventListener("click",()=>diagnostics().catch(error=>record("diagnostics","failure",{error:error.message})));
$("register").addEventListener("click",async()=>{try{const token=$("sessionToken").value.trim();if(!token)throw new Error("session_token_required");const start=await api("/v1/identity/passkeys/registration/options",{method:"POST",headers:{authorization:"Bearer "+token},body:JSON.stringify({label:$("label").value})});const credential=await navigator.credentials.create({publicKey:creationOptions(start.options)});if(!credential)throw new Error("credential_not_created");const result=await api("/v1/identity/passkeys/registration/verify",{method:"POST",headers:{authorization:"Bearer "+token},body:JSON.stringify({challengeId:start.challengeId,response:registrationJSON(credential)})});record("registration","success",{passkey:{deviceType:result.passkey.deviceType,backedUp:result.passkey.backedUp,transports:result.passkey.transports}});}catch(error){record("registration","failure",{error:error.name??"Error",code:error.message});}});
$("authenticate").addEventListener("click",async()=>{try{const start=await api("/v1/identity/passkeys/authentication/options",{method:"POST",body:"{}"});const credential=await navigator.credentials.get({publicKey:requestOptions(start.options)});if(!credential)throw new Error("credential_not_returned");const result=await api("/v1/identity/passkeys/authentication/verify",{method:"POST",body:JSON.stringify({challengeId:start.challengeId,response:authenticationJSON(credential)})});$("sessionToken").value=result.sessionToken;record("authentication","success",{sessionIssued:true});}catch(error){record("authentication","failure",{error:error.name??"Error",code:error.message});}});
$("download").addEventListener("click",()=>{const blob=new Blob([JSON.stringify({...evidence,completedAt:new Date().toISOString()},null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="phoenix-passkey-evidence-"+Date.now()+".json";link.click();URL.revokeObjectURL(link.href);});
$("clear").addEventListener("click",()=>{$("sessionToken").value="";evidence.events.length=0;$("log").textContent="";});
diagnostics().catch(error=>record("diagnostics","failure",{error:error.message}));
`;

export const passkeyValidationHarness: FastifyPluginAsync = async (app) => {
  const common = { "cache-control": "no-store", "x-robots-tag": "noindex, nofollow", "cross-origin-resource-policy": "same-origin" };
  app.get("/", async (_request: FastifyRequest, reply: FastifyReply) => reply.headers(common).type("text/html; charset=utf-8").send(html));
  app.get("/style.css", async (_request: FastifyRequest, reply: FastifyReply) => reply.headers(common).type("text/css; charset=utf-8").send(css));
  app.get("/app.js", async (_request: FastifyRequest, reply: FastifyReply) => reply.headers(common).type("text/javascript; charset=utf-8").send(javascript));
};
