import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
const fail=(message)=>{console.error(message);process.exitCode=1;};const read=(name)=>fs.readFileSync(name,"utf8");const parse=(name)=>JSON.parse(read(name));
const required=["package.json","package-lock.json","tsconfig.json","tsconfig.check.json","src/app.ts","src/main.ts","src/identity/email.ts","src/identity/password.ts","src/identity/token-crypto.ts","src/identity/distributed-rate-limit.ts","src/identity/repository.ts","src/identity/routes.ts","src/identity/service.ts","migrations/001_identity.sql","migrations/002_identity_hardening.sql","migrations/003_identity_slice2.sql","scripts/migrate.ts","scripts/security-check.mjs","Dockerfile","VERSION.json","README.md","SECURITY.md","FILE_MANIFEST.json","CHECKSUMS.sha256",".github/workflows/ci.yml",".github/workflows/codeql.yml",".github/workflows/dependency-review.yml",".github/dependabot.yml"];
for(const file of required)if(!fs.existsSync(file))fail(`Missing required file: ${file}`);if(process.exitCode)process.exit();
const pkg=parse("package.json"),lock=parse("package-lock.json"),version=parse("VERSION.json"),manifest=parse("FILE_MANIFEST.json"),readme=read("README.md"),security=read("SECURITY.md"),system=read("src/routes/system.ts");
if(pkg.version!==version.version)fail("package.json and VERSION.json versions differ");if(lock.version!==version.version||lock.packages?.[""]?.version!==version.version)fail("package-lock version differs");if(manifest.repository_version!==version.version)fail("manifest version differs");
if(!readme.includes("3.4.0")||!readme.includes("Identity Slice 2"))fail("README authority is stale");if(!security.includes("email verification")||!security.includes("password recovery"))fail("SECURITY does not cover Slice 2");if(!system.includes("app.config.version")||/version:\s*["']3\./.test(system))fail("system route version is hard-coded");if(version.production_ready!==false||version.status!=="candidate")fail("release state is unsafe");
const ignored=new Set([".git","node_modules","dist"]);function walk(dir="."){const out=[];for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(entry.isDirectory()&&ignored.has(entry.name))continue;const full=path.join(dir,entry.name);if(entry.isDirectory())out.push(...walk(full));else if(entry.isFile())out.push(full.replace(/^\.\//,"").replaceAll("\\","/"));}return out;}
const actual=walk().filter(f=>f!=="CHECKSUMS.sha256").sort(),listed=[...manifest.files].sort();if(JSON.stringify(actual)!==JSON.stringify(listed)){const a=new Set(actual),l=new Set(listed);const extra=actual.filter(f=>!l.has(f)),missing=listed.filter(f=>!a.has(f));if(extra.length)console.error(`Unmanaged files:\n- ${extra.join("\n- ")}`);if(missing.length)console.error(`Missing files:\n- ${missing.join("\n- ")}`);fail("FILE_MANIFEST does not exactly match repository files");}if(manifest.file_count!==listed.length)fail("manifest count incorrect");
for(const line of read("CHECKSUMS.sha256").trim().split("\n")){if(!line)continue;const match=/^([a-f0-9]{64})  (.+)$/.exec(line);if(!match){fail(`Invalid checksum: ${line}`);continue;}const[,expected,file]=match;if(!fs.existsSync(file)){fail(`Checksum missing file: ${file}`);continue;}const actualHash=createHash("sha256").update(fs.readFileSync(file)).digest("hex");if(actualHash!==expected)fail(`Checksum mismatch: ${file}`);}
const lockText=read("package-lock.json");if(lockText.includes("internal.api.openai.org")||lockText.includes("applied-caas-gateway"))fail("private registry URL found");if(!process.exitCode)console.log("Repository constitutional consistency checks passed.");
